// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Your consoles ip address": {"en": "Your consoles ip adress", "de": "IP-Adresse deiner Xbox"},
    "Your consoles live id": {"en": "Your consoles live id", "de": "Live ID deiner Xbox"},
    "Authenticate on Xbox Live": {"en": "Authenticate on Xbox Live", "de": "Authentifizierung bei Xbox Live"},
    "E-mail address": {"en": "E-mail address", "de": "E-Mail Adresse"},
    "Password": {"en": "Password", "de": "Passwort"},
    "Please provide your Xbox Live account information": {"en": "Please enter your Xbox Live account information", "de": "Bitte Xbox Live Account Daten eingeben"}
};