// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'Your consoles ip address or hostname': {
        "en": `Your consoles ip address or hostname'`,
        "de": `IP-Adresse oder Hostname Ihrer Konsole '`,
        "ru": `Ваш IP-адрес консоли или имя хоста '`,
        "pt": `O endereço IP ou o nome do host de seus consoles '`,
        "nl": `Het IP-adres of de hostnaam van uw console '`,
        "fr": `Adresse IP ou nom d'hôte de votre console »`,
        "it": `Indirizzo IP o nome host della tua console "`,
        "es": `Su dirección IP o nombre de host de la consola '`,
        "pl": `Twój adres IP lub nazwa hosta „`,
        "zh-cn": `您的控制台IP地址或主机名”`
    },
    'Your consoles live id': {
        "en": `Live Id of your console`,
        "de": `Live ID Ihrer Konsole`,
        "ru": `Live Id вашей консоли`,
        "pt": `Live ID do seu console`,
        "nl": `Live-id van uw console`,
        "fr": `ID en direct de votre console`,
        "it": `ID live della tua console`,
        "es": `Identificación en vivo de tu consola`,
        "pl": `Identyfikator na żywo Twojej konsoli`,
        "zh-cn": `控制台的实时ID`    },
    'Authenticate on Xbox Live': {
        "en": `Authentication on Xbox Live`,
        "de": `Authentifizierung auf Xbox Live`,
        "ru": `Аутентификация в Xbox Live`,
        "pt": `Autenticação no Xbox Live`,
        "nl": `Verificatie op Xbox Live`,
        "fr": `Authentification sur Xbox Live`,
        "it": `Autenticazione su Xbox Live`,
        "es": `Autenticación en Xbox Live`,
        "pl": `Uwierzytelnianie w Xbox Live`,
        "zh-cn": `Xbox Live上的身份验证`
    },
    'E-mail address': {
        "en": `E-mail address`,
        "de": `E-Mail-Addresse`,
        "ru": `Адрес электронной почты`,
        "pt": `Endereço de e-mail`,
        "nl": `E-mailadres`,
        "fr": `Adresse électronique`,
        "it": `Indirizzo email`,
        "es": `Dirección de correo electrónico`,
        "pl": `Adres e-mail`,
        "zh-cn": `电子邮件地址`    },
    'Password': {
        "en": `Password`,
        "de": `Passwort`,
        "ru": `пароль`,
        "pt": `Senha`,
        "nl": `Wachtwoord`,
        "fr": `Mot de passe`,
        "it": `Parola d'ordine`,
        "es": `Contraseña`,
        "pl": `Hasło`,
        "zh-cn": `密码`
    },
    'Please provide your Xbox Live account information': {
        "en": `Please provide your Xbox Live account information`,
        "de": `Bitte geben Sie Ihre Xbox Live Account Daten an`,
        "ru": `Пожалуйста, предоставьте информацию о вашей учетной записи Xbox Live`,
        "pt": `Forneça as informações da sua conta do Xbox Live`,
        "nl": `Geef uw Xbox Live-accountgegevens op`,
        "fr": `Veuillez fournir les informations de votre compte Xbox Live`,
        "it": `Fornisci le informazioni del tuo account Xbox Live`,
        "es": `Proporcione la información de su cuenta de Xbox Live`,
        "pl": `Podaj informacje o koncie Xbox Live`,
        "zh-cn": `请提供您的Xbox Live帐户信息`
    }
};